### ISSUE TITLE
5.2.1: Disable Counter Animation (Toggle W/ Multicontroller Tilt Right) not working fine

### ISSUE THREAD

**Issue by Tristan-cx5** [Trevelopment/MZD_Speedometer#1]
Hi Trez,

thanks for the cool installer & features of Speedometer 5.2.1, but "Disable Counter Animation (Toggle W/ Multicontroller Tilt Right)" seems to not work as it should on my cx5/2016/automatic/56.00.513C EU. Tested behaviour of Multicontroller in Speedometer 5.2.1:
- tap on the multicontroller: switches rows. works fine.
- move to left: background changes (cool feature). works fine.
- move to right: nothing visible happens - but it should disable the counter animation (the raising bars left of the big main value)
- move up (towards front of car): km/h and mph are switched - but not temperature C and F - [screenshot](https://www.dropbox.com/s/ak7r45lya4nphdy/521_mph_but_C_and_not_F.jpg?dl=0).
- move down (towards rear of the car): counter animation left of main value is shorter than before, but does not disappear completely while driving. At 0 km/h it disappears completely. See Screenshots: [One](https://www.dropbox.com/s/ucdeuxjfja618fz/521_counter_animation_0kmh_disabled_no_show_OK.jpg?dl=0), [Two](https://www.dropbox.com/s/ed3oode0shsupiy/521_counter_animation_0kmh_normal.jpg?dl=0), [Three](https://www.dropbox.com/s/33yayc0zkdn4z9c/521_counter_animation_6kmh_disabled_no_show_OK.jpg?dl=0), [Four](https://www.dropbox.com/s/dy7h5el8yja06k3/521_counter_animation_6kmh_normal.jpg?dl=0).

And I did a [video](https://www.dropbox.com/s/pqkq94o2usiqaik/521_some.mp4?dl=0) of some Multicontroller moves.

**Comment by Trevelopment** [comment]
OK those are all working as expected.  Down toggles the bar from speed to engine speed.  right just toggles the counter animation on the *Number* but not the bar.  I could make down toggle the bar on/off for you if you want here just replace `config/speedometer_mod/jci/gui/apps/_speedometer/js/speedometerUpdate.js` with [this](https://raw.githubusercontent.com/Trevelopment/MZD_Speedometer/master/config/speedometer_mod/jci/gui/apps/_speedometer/js/speedometerUpdate.js) (you can do a right-click save as on that link)

**Comment by Tristan-cx5** [comment]
Thanks for clarification of my obviously not so properly done test & providing the special file, which I really appreciate & will test it tonight.

**Comment by Tristan-cx5** [comment]
Thanks for the special file - it works great. 
Screenshots: 
[- Before - bar is displayed ](https://www.dropbox.com/s/qmdp9gx371tur1b/Speedo_bar_on_left_displayed.JPG?dl=0)
[- After - bar not displayed](https://www.dropbox.com/s/vcp4a8hsklx5ype/Speedo_NO_bar_on_left_displayed.JPG?dl=0)

**Comment by Trevelopment** [comment]
Yea I tried it too I'm debating on making down a 3 way toggle for speed eng speed and off
