### ISSUE TITLE
Speedometer 5.3: One part of the main value is too close to the km/h

### ISSUE THREAD

**Issue by Tristan-cx5** [Trevelopment/MZD_Speedometer#2]
Speedometer 5.3: Right part of a 3 digit main value (e.g.speed) is too close to the km/h. There should be a small gap. See [this screenhot](https://www.dropbox.com/s/xbzrfr0bsmzykfn/speedo_main_value_display_bug.JPG?dl=0). It´s not a critical bug.

**Comment by Trevelopment** [comment]
Hey you can get v5.5 at http://speedo.mazdatweaks.win or on the releases page.

**Comment by Tristan-cx5** [comment]
Thanks
